# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: hulto cyber security blog
google_analytics: hulto cyber security blog
title: Hul.to

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Hul.to

description: My personal site for blog posts and guides.
author:
  name: Hulto
  email: hulto@hul.to 
  github: hulto
  twitter: hultoko
  bio: Cyber security professional with a passion for rootkits, automation, and exploits.

categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
  - jekyll-spaceship
